name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    uses: ./.github/workflows/on-workflow-call-format.yml
    secrets: inherit

  lint:
    uses: ./.github/workflows/on-workflow-call-lint.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/on-workflow-call-build.yml
    secrets: inherit

  check:
    needs: [format, lint, build]
    uses: ./.github/workflows/on-workflow-call-check.yml
    secrets: inherit

  release:
    if: needs.check.outputs.publish == 'yes' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [check]
    uses: ./.github/workflows/on-workflow-call-release.yml
    secrets: inherit
